Enable custom cert for app
kartverket/skiperator pull request #481
Opened 2024-06-25 11:21 UTC by BardOve

To enable support for custom certificates in skiperator applications, we add a field customCertificate to the application spec. This  points to a tls secret in istio-gateways namespace to use in gateway resource.

2024-06-25 13:16 UTC, evenh requested changes
After looking through the code and giving it some thought I think there's two major unhandled issues.

### Routing
We'll need to handle the `controllers/routing` package as well. 

### Hostnames
An application can have multiple hostnames. Right now we're just overriding with whatever custom certificate secret that's passed without considering whether this is for an internal or an external ingress, or if the hostname in the gateway matches whatever is present in the certificate secret.

I suggest that we team up and fix those issues together :-)

2024-06-25 13:16 UTC, evenh commented on controllers/application/certificate.go
> +			if secret.Type != "kubernetes.io/tls" {
Required import:
```
corev1 "k8s.io/api/core/v1"
```

```suggestion
			if secret.Type != corev1.SecretTypeTLS {
```

2024-07-01 09:00 UTC, martinhny commented on api/v1alpha1/application_types.go
> +	// They can optionally be suffixed with a plus and name of a custom TLS secret located in the istio-gateways namespace.
I think we should have a CustomCerts type or turn this one into an interface which accepts both an object and string, although this is a dirty solution as well. Or will this make reconciling very difficult?

2024-07-01 10:03 UTC, evenh commented on config/crd/skiperator.kartverket.no_applications.yaml
> -    controller-gen.kubebuilder.io/version: v0.15.0
Nope, a side effect of looking up binaries in `$PATH` before `$GOBIN`. Fixed in Makefile :)

2024-07-01 10:13 UTC, evenh commented on api/v1alpha1/hosts.go
> +	}
My thoughts exactly as well. We might be in a situation where applications are deployed before DNS are provisioned.

2024-07-03 11:43 UTC, evenh commented on controllers/application/controller.go
> +			errMessage := fmt.Sprintf("ingress with value '%s' was not valid. ingress must be lower case, contain no spaces, be a non-empty string, and have a hostname/domain separated by a period", h.Hostnam
With the time available before the holidays I couldn't get the tests to pass when rewriting this section. Happy to team up in August.

2024-07-03 11:43 UTC, evenh approved these changes

2024-07-03 11:43 UTC, merged